CREATE TABLE "users" (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "latest_theme" TEXT REFERENCES "themes"(id) ON DELETE CASCADE,
    "create_date" TIMESTAMPTZ DEFAULT now() NOT NULL    
);

DROP TYPE IF EXISTS "user_type";
CREATE TYPE "user_type" AS ENUM (
    'admin',
    'user'
);